# Generated by Django 4.2 on 2025-11-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='country',
            field=models.CharField(blank=True, db_index=True, help_text='ISO country code (e.g., us, gb, in)', max_length=10, null=True),
        ),
    ]
